name: Android Nightly

on:
  push:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/nightly.yml'
  workflow_dispatch:

jobs:
  build:
    environment: Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/fvm
          key: ${{ runner.os }}-pub-gradle-android-fvm-${{ hashFiles('**/pubspec.lock', '**/*.gradle', '**/pom.xml', '**/.fvmrc') }}
          restore-keys: |
            ${{ runner.os }}-pub-gradle-android-fvm-

      - uses: dart-lang/setup-dart@v1.4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - run: dart pub global activate fvm
      - run: fvm install
      - run: fvm flutter pub get
      - run: fvm flutter analyze
        continue-on-error: true

      - name: Set up local.properties for GitHub
        run: |
          echo "GITHUB_ACTOR=zhai23" >> android/local.properties
          echo "GITHUB_TOKEN=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" >> android/local.properties

      - run: fvm flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk
#      - name: Upload golden failures
#        uses: actions/upload-artifact@v4
#        with:
#          name: goldens-failures
#          path: test/components/failures/
#          if-no-files-found: 'ignore'
