name: Android Nightly

on:
  push:
    paths:
      - 'android/**'
      - 'lib/**'
      - 'lang/**'
      - 'fonts/**'
      - 'pubspec*'
      - 'pigeons/**'
      - 'test/**'
      - '.github/workflows/nightly.yml'
  workflow_dispatch:

jobs:
  build:
    environment: Nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ~/fvm
          key: ${{ runner.os }}-pub-gradle-android-fvm-${{ hashFiles('**/pubspec.lock', '**/*.gradle', '**/pom.xml', '**/.fvmrc') }}
          restore-keys: |
            ${{ runner.os }}-pub-gradle-android-fvm-

      - uses: dart-lang/setup-dart@v1.4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Decode keystore
        run: echo "${{ secrets.KEY_JKS }}" | base64 -d > android/key.jks

      - name: Write key.properties
        run: |
          cat > android/key.properties <<EOF
          storeFile=key.jks
          storePassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=upload
          keyPassword=${{ secrets.ALIAS_PASSWORD }}
          EOF

      - run: dart pub global activate fvm
      - run: fvm install
      - run: fvm flutter pub get
      - run: fvm flutter analyze
        continue-on-error: true

      # 可选：如需测试，取消注释
      # - name: Flutter test
      #   continue-on-error: true
      #   run: fvm flutter test

      - name: Build release APK
        run: fvm flutter build apk --release
        env:
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTLY: 'true'

      - uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk

      # 可选：上传 golden 测试失败快照
      # - name: Upload golden failures
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: goldens-failures
      #     path: test/components/failures/
      #     if-no-files-found: 'ignore'
